name: Ubuntu Configuration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run configuration
      run: |
        cd ./ubuntu
        bash ubuntu-config.sh
        
